### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by JIzabal** [therab6it/week2-lab-report#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
  - Put the lab report on another markdown file that isn't index.md
- [x] Last example counts keystrokes and shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by therab6it** [comment]
I have removed the contents from index.md and put them up on report-page.md. Would that suffice?

**Comment by therab6it** [comment]
https://therab6it.github.io/week2-lab-report/report-page.html

**Comment by JIzabal** [comment]
Looks good! I don't think I got your regrade request, so please follow the template above to receive credit.
